import type {NextPage} from 'next';
import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';
import MainContent from "../components/MainContent";
import Alerts from "../components/Alerts";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Autobet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <MainContent/>
                <Alerts/>
            </main>
        </div>
    );
}

export default Home;
