name: "Close inactive issues"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 25 days with no activity. Remove inactive label or comment or this will be closed in 5 days'
        stale-issue-label: 'inactive'
        only-labels: 'awaiting response'
        days-before-stale: 25
        days-before-close: 5
        close-issue-message: 'This issue is closed because it has been open 30 days with no activity'
